version: '3.7'
services:
  makepkg:
    container_name: makepkg
    image: makepkg
    command: /opt/makepkg/build.sh
    environment:
      PKG_NAME: ${PKG_NAME}
      PKG_VERSION: ${PKG_VERSION}
      GIT_HASH: ${GIT_HASH}
    volumes:
     - type: bind
       source: $PWD
       target: /opt/makepkg
       read_only: false
    build:
     context: ./makepkg
